title: 0v3rf10w
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf
owner: 0v3rf10w

# for a clean URL
#permalink: :slug
permalink:  /:title/
baseurl: /
url: pwnk1dd13.github.io

social:
  twitter: _0v3rf10w
  github: pwnk1dd13

plugins:
 - jekyll-seo-tag
 - jekyll-paginate

paginate: 3

### comments & analytics
hyvor_talk_website_id: 1078
google_analytics: UA-168628548-1
